language: rust
sudo: false
rust:
  - beta
  - nightly
  - stable
os:
  - linux
addons:
  apt:
    packages:
    - libsdl2-dev
before_script:
  - rustc -V
  - cargo -V
script:
  - cargo build --release -v
  - cargo test -v
notifications:
  email:
    recipients:
      - reangd@yandex.ru
    on_success: never
    on_failure: always