[package]
name = "rust-software-render"
version = "0.4.0"
authors = ["ReanGD"]

[dependencies]
time = "0.1.32"
sdl2 = "0.8.0"
cgmath = "0.2.0"
libc = "0.1.10"
sdl2-sys = "0.6.2"
sdl2_image = "0.2.5"
obj = "0.3.0"
genmesh = "0.3.*"
