[package]
name = "rust-software-render"
version = "0.4.0"
authors = ["ReanGD"]

[dependencies]
rand = "*"
time = "*"
sdl2 = "0.8.0"
cgmath = "*"
libc = "*"
sdl2-sys = "*"
obj = "0.2.2"

[dependencies.sdl2_image]
git = "https://github.com/xsleonard/rust-sdl2_image"
